(()=>{
const SB_URL='https://fzpffyouubmbxfwycywg.supabase.co',SB_KEY='sb_publishable_fqG3I5cRWBXjn-EP0FoATA_0-SWvfsR';
let busy=false,lastScheduleId=null;
function session(){try{return JSON.parse(localStorage.getItem('ieadjo_member_session')||'null')}catch{return null}}
async function api(path,o={}){const s=session();const h={'apikey':SB_KEY,'Content-Type':'application/json',...(o.headers||{})};if(s?.access_token)h.Authorization='Bearer '+s.access_token;const r=await fetch(SB_URL+path,{...o,headers:h,cache:'no-store'});let d=null;try{d=await r.json()}catch{}if(!r.ok)throw new Error(d?.message||d?.error_description||'Não foi possível atualizar a presença.');return d}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function initials(name){const a=String(name||'Integrante').trim().split(/\s+/);return ((a[0]?.[0]||'I')+(a.length>1?(a[a.length-1][0]||''):'')).toUpperCase()}
function avatar(member){const name=member.member_name||member.name||'Integrante';if(member.photo)return `<img src="${esc(member.photo)}" alt="Foto de ${esc(name)}" style="width:100%;height:100%;object-fit:cover;display:block">`;return `<span style="font-size:11px;font-weight:900;color:#0e2a47">${esc(initials(name))}</span>`}
async function data(){const s=session();if(!s?.user?.id)return null;const today=new Date();today.setHours(0,0,0,0);const iso=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;const [sched,roster,members,allMembers]=await Promise.all([
 api('/rest/v1/ieadjo_schedules?select=id,event_date,title,time_text&event_date=gte.'+iso+'&order=event_date.asc,id.asc&limit=1'),
 api('/rest/v1/rpc/ieadjo_schedule_roster',{method:'POST',body:'{}'}),
 api('/rest/v1/ieadjo_members?select=id,user_id,name&user_id=eq.'+encodeURIComponent(s.user.id)+'&limit=1'),
 api('/rest/v1/ieadjo_members?select=id,name,photo&approved=eq.true&access_status=eq.approved')
]);
const next=sched?.[0];if(!next)return null;const photoById=new Map((allMembers||[]).map(m=>[m.id,m.photo||'']));const r=(roster||[]).filter(x=>x.schedule_id===next.id).map(x=>({...x,photo:photoById.get(x.member_id)||''}));const me=members?.[0]||null;return {next,roster:r,me,myRow:me?r.find(x=>x.member_id===me.id):null};}
function statusLabel(st){return st==='confirmed'?'✓ Presença confirmada':st==='declined'?'Não vou conseguir ir':'Confirmar presença'}
async function setAttendance(scheduleId,memberId,status){await api('/rest/v1/ieadjo_schedule_members?schedule_id=eq.'+encodeURIComponent(scheduleId)+'&member_id=eq.'+encodeURIComponent(memberId),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({attendance_status:status,attendance_updated_at:new Date().toISOString()})});await refresh(true)}
function bindButton(oldBtn,status,ctx){if(!oldBtn||oldBtn.dataset.attendanceBound===status)return;const b=oldBtn.cloneNode(true);b.dataset.attendanceBound=status;b.textContent=status==='confirmed'?'✓ Presença confirmada':status==='declined'?'Não posso ir':oldBtn.id==='cant'?'Não posso ir':'Confirmar presença';if(b.id==='confirm')b.className=status==='confirmed'?'success':'primary';b.onclick=async e=>{e.preventDefault();e.stopPropagation();if(!ctx.myRow){alert('Você não está incluído nesta escala.');return}b.disabled=true;try{await setAttendance(ctx.next.id,ctx.me.id,b.id==='confirm'?'confirmed':'declined')}catch(err){alert(err.message)}finally{b.disabled=false}};oldBtn.replaceWith(b)}
function render(ctx){const hero=document.querySelector('.hero');if(!hero)return;lastScheduleId=ctx.next.id;let box=hero.querySelector('#attendanceSummary');if(!box){box=document.createElement('div');box.id='attendanceSummary';box.style.cssText='margin:12px 0 14px;padding:11px 12px;border-radius:14px;background:#ffffff10;border:1px solid #ffffff20';const actions=hero.querySelector('.actions');actions?.before(box)}const yes=ctx.roster.filter(x=>x.attendance_status==='confirmed');const pending=ctx.roster.filter(x=>!x.attendance_status||x.attendance_status==='pending');const no=ctx.roster.filter(x=>x.attendance_status==='declined');const faces=yes.length?`<div style="display:flex;align-items:center;flex-wrap:wrap;gap:8px;margin-top:9px">${yes.map(x=>`<div title="${esc(x.member_name)}" style="display:flex;align-items:center;gap:6px;max-width:145px"><div style="width:34px;height:34px;border-radius:50%;overflow:hidden;background:#d5ad58;display:grid;place-items:center;flex:none;border:2px solid #ffffffcc">${avatar(x)}</div><span style="font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${esc(x.member_name)}</span></div>`).join('')}</div>`:'<div style="font-size:12px;line-height:1.45;margin-top:6px;opacity:.75">Ninguém confirmou ainda.</div>';box.innerHTML=`<div style="display:flex;justify-content:space-between;gap:8px;align-items:center"><b style="font-size:12px">✅ Presenças confirmadas</b><span style="font-size:11px;opacity:.8">${yes.length}/${ctx.roster.length}</span></div>${faces}${pending.length?`<div style="font-size:10px;opacity:.7;margin-top:8px">Aguardando: ${esc(pending.map(x=>x.member_name).join(', '))}</div>`:''}${no.length?`<div style="font-size:10px;opacity:.7;margin-top:3px">Não poderão ir: ${esc(no.map(x=>x.member_name).join(', '))}</div>`:''}`;
const st=ctx.myRow?.attendance_status||'pending';bindButton(hero.querySelector('#confirm'),st,ctx);bindButton(hero.querySelector('#cant'),st,ctx);const confirm=hero.querySelector('#confirm');if(confirm)confirm.textContent=statusLabel(st);}
async function refresh(force=false){if(busy)return;const hero=document.querySelector('.hero');if(!hero)return;busy=true;try{const ctx=await data();if(ctx)render(ctx)}catch(e){console.warn('Presenças:',e)}finally{busy=false}}
const obs=new MutationObserver(()=>setTimeout(()=>refresh(),120));obs.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('load',()=>setTimeout(()=>refresh(true),350));setInterval(()=>refresh(true),30000);
})();