(()=>{
if(window.__ieadjoChat)return;window.__ieadjoChat=true;
const U='https://fzpffyouubmbxfwycywg.supabase.co',K='sb_publishable_fqG3I5cRWBXjn-EP0FoATA_0-SWvfsR';let last=null,busy=false;
const ses=()=>{try{return JSON.parse(localStorage.getItem('ieadjo_member_session')||'null')}catch{return null}};
const prof=()=>{try{return JSON.parse(localStorage.getItem('ieadjo_member_profile')||'null')||{}}catch{return {}}};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function api(path,opt={}){let s=ses();if(!s?.access_token)return null;let r=await fetch(U+path,{...opt,cache:'no-store',headers:{apikey:K,Authorization:'Bearer '+s.access_token,'Content-Type':'application/json',...(opt.headers||{})}});if(!r.ok)throw Error('chat');try{return await r.json()}catch{return null}}
function badge(n){document.querySelectorAll('[data-chat-badge]').forEach(x=>x.remove());if(!n)return;let b=document.querySelector('.nav [data-go="chat"]');if(!b)return;let s=document.createElement('i');s.dataset.chatBadge='1';s.textContent=n>9?'9+':n;s.style.cssText='position:absolute;margin:-27px 0 0 25px;background:#d64545;color:white;border-radius:20px;min-width:17px;height:17px;padding:0 4px;font:700 10px/17px sans-serif;font-style:normal';b.style.position='relative';b.appendChild(s)}
function notify(r){if(document.visibilityState==='visible'&&window.tab==='chat')return;if('Notification'in window&&Notification.permission==='granted')new Notification('IEADJO • Nova mensagem',{body:(r.member_name||'Integrante')+': '+r.message,icon:'/igreja-hq.jpg',tag:'ieadjo-chat'});}
async function poll(){if(busy)return;busy=true;try{let rows=await api('/rest/v1/ieadjo_chat_messages?select=id,user_id,member_name,message,created_at&order=created_at.desc&limit=50');if(!rows)return;rows.reverse();let newest=rows.at(-1);if(last&&newest&&newest.id!==last){let s=ses(),fresh=rows.filter(x=>String(x.id)>String(last)&&x.user_id!==s?.user?.id);if(fresh.length){let unread=Number(localStorage.getItem('ieadjo_chat_unread')||0)+fresh.length;localStorage.setItem('ieadjo_chat_unread',unread);badge(unread);notify(fresh.at(-1))}}if(newest)last=newest.id;window.__ieadjoChatRows=rows;if(window.tab==='chat')draw(rows)}catch(e){console.warn('chat',e)}finally{busy=false}}
function draw(rows){let v=document.getElementById('view');if(!v)return;let chat=v.querySelector('.chat');if(!chat)return;let s=ses();chat.innerHTML=rows.map(r=>`<div class="bubble ${r.user_id===s?.user?.id?'mine':''}"><b>${esc(r.user_id===s?.user?.id?'Você':r.member_name||'Integrante')}</b><p>${esc(r.message)}</p><small>${new Date(r.created_at).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</small></div>`).join('')||'<div class="muted">Nenhuma mensagem ainda.</div>';localStorage.setItem('ieadjo_chat_unread','0');badge(0)}
async function send(text){let s=ses(),p=prof();await api('/rest/v1/ieadjo_chat_messages',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({user_id:s.user.id,member_name:p.name||s.user.user_metadata?.full_name||'Integrante',message:text})});await poll()}
document.addEventListener('click',async e=>{let sendBtn=e.target.closest('#send');if(sendBtn&&window.tab==='chat'){e.preventDefault();e.stopImmediatePropagation();let i=document.getElementById('msg'),t=i?.value.trim();if(t){i.value='';await send(t)}}let chatBtn=e.target.closest('[data-go="chat"]');if(chatBtn){localStorage.setItem('ieadjo_chat_unread','0');badge(0);setTimeout(poll,80)}},true);
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target?.id==='msg'){e.preventDefault();document.getElementById('send')?.click()}},true);
if('Notification'in window&&Notification.permission==='default')document.addEventListener('click',()=>Notification.requestPermission().catch(()=>{}),{once:true});
badge(Number(localStorage.getItem('ieadjo_chat_unread')||0));poll();setInterval(poll,5000);
})();