(()=>{
if(window.__ieadjoTeam)return;window.__ieadjoTeam=true;
const U='https://fzpffyouubmbxfwycywg.supabase.co',K='sb_publishable_fqG3I5cRWBXjn-EP0FoATA_0-SWvfsR';
const getJSON=k=>{try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return null}};
const ses=()=>getJSON('ieadjo_member_session');
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function api(path,opt={}){const s=ses();if(!s?.access_token)throw new Error('Sessão expirada.');const r=await fetch(U+path,{...opt,cache:'no-store',headers:{apikey:K,Authorization:'Bearer '+s.access_token,'Content-Type':'application/json',...(opt.headers||{})}});let d=null;try{d=await r.json()}catch{}if(!r.ok)throw new Error(d?.message||d?.error||'Não foi possível carregar.');return d}
function addHomeButton(){const view=document.getElementById('view');if(!view?.querySelector('.hello'))return;const grid=view.querySelector('.grid');if(!grid||grid.querySelector('[data-team-go]'))return;const b=document.createElement('button');b.type='button';b.setAttribute('data-team-go','1');b.innerHTML='<span class="ico">👥</span><b>Nossa equipe</b><small>Fotos e integrantes</small>';grid.appendChild(b)}
function initials(name){const a=String(name||'Integrante').trim().split(/\s+/);return ((a[0]?.[0]||'I')+(a.length>1?a[a.length-1][0]||'':'')).toUpperCase()}
async function renderTeam(){const view=document.getElementById('view');if(!view)return;view.innerHTML='<div class="pagehead"><h1>Nossa equipe</h1><p>Conheça os integrantes do ministério e demonstre honra.</p></div><div id="teamList"><div class="muted">Carregando equipe...</div></div>';
try{const [members,honors]=await Promise.all([api('/rest/v1/ieadjo_members?select=id,name,role_text,photo,bio,user_id&approved=eq.true&access_status=eq.approved&order=name.asc'),api('/rest/v1/ieadjo_member_honors?select=id,target_member_id,user_id')]);const uid=ses()?.user?.id,box=document.getElementById('teamList');if(!box)return;box.innerHTML=members.map(m=>{const mine=honors.some(h=>h.target_member_id===m.id&&h.user_id===uid),count=honors.filter(h=>h.target_member_id===m.id).length;const avatar=m.photo?`<img src="${esc(m.photo)}" alt="Foto de ${esc(m.name)}" style="width:100%;height:100%;object-fit:cover">`:`<span style="font-weight:900;color:#0e2a47">${esc(initials(m.name))}</span>`;return `<article style="background:#fff;border:1px solid #e5eaf0;border-radius:18px;padding:14px;margin-top:10px;display:flex;gap:13px;align-items:center"><div style="width:62px;height:62px;border-radius:50%;overflow:hidden;background:#d5ad58;display:grid;place-items:center;flex:none">${avatar}</div><div style="min-width:0;flex:1"><b style="font-size:15px">${esc(m.name)}</b><div style="font-size:12px;color:#174f7c;font-weight:800;margin-top:2px">${esc(m.role_text||'Integrante')}</div>${m.bio?`<div style="font-size:11px;color:#6c7a89;margin-top:5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${esc(m.bio)}</div>`:''}<button data-honor="${m.id}" data-on="${mine?'1':'0'}" style="margin-top:8px;border:0;border-radius:10px;padding:8px 10px;background:${mine?'#e8f7ef':'#eef4f9'};color:${mine?'#206b47':'#0e2a47'};font-weight:800">🙌 ${mine?'Honrado':'Honrar'} • ${count}</button></div></article>`}).join('')||'<div class="muted">Nenhum integrante disponível.</div>';box.querySelectorAll('[data-honor]').forEach(b=>b.onclick=()=>toggleHonor(b));}catch(e){const box=document.getElementById('teamList');if(box)box.innerHTML=`<div style="color:#9b3838;font-size:12px">${esc(e.message)}</div>`}}
async function toggleHonor(btn){const id=Number(btn.dataset.honor),on=btn.dataset.on==='1',uid=ses()?.user?.id;if(!uid)return;btn.disabled=true;try{if(on)await api('/rest/v1/ieadjo_member_honors?target_member_id=eq.'+id+'&user_id=eq.'+uid,{method:'DELETE'});else await api('/rest/v1/ieadjo_member_honors',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({target_member_id:id,user_id:uid})});await renderTeam()}catch(e){alert(e.message)}finally{btn.disabled=false}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-team-go]');if(!b)return;e.preventDefault();e.stopPropagation();renderTeam()},true);
function watch(){const view=document.getElementById('view');if(!view){setTimeout(watch,100);return}new MutationObserver(()=>addHomeButton()).observe(view,{childList:true,subtree:false});addHomeButton()}
watch();
})();