(()=>{
if(window.__ieadjoChatSafe)return;window.__ieadjoChatSafe=true;
const U='https://fzpffyouubmbxfwycywg.supabase.co',K='sb_publishable_fqG3I5cRWBXjn-EP0FoATA_0-SWvfsR';let rows=[],lastId=null,busy=false;
const getJSON=k=>{try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return null}};
const ses=()=>getJSON('ieadjo_member_session');const prof=()=>getJSON('ieadjo_member_profile')||{};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function api(path,opt={}){const s=ses();if(!s?.access_token)return null;const r=await fetch(U+path,{...opt,cache:'no-store',headers:{apikey:K,Authorization:'Bearer '+s.access_token,'Content-Type':'application/json',...(opt.headers||{})}});if(!r.ok)return null;if(r.status===204)return [];try{return await r.json()}catch{return []}}
function isChat(){return document.querySelector('#view .pagehead h1')?.textContent.trim()==='Chat geral'}
function badge(n){document.querySelectorAll('[data-chat-badge]').forEach(x=>x.remove());if(!n)return;const b=document.querySelector('.nav [data-go="chat"]');if(!b)return;b.style.position='relative';const x=document.createElement('i');x.dataset.chatBadge='1';x.textContent=n>9?'9+':String(n);x.style.cssText='position:absolute;top:7px;right:18px;background:#d64545;color:#fff;border-radius:20px;min-width:17px;height:17px;padding:0 4px;font:700 10px/17px sans-serif;font-style:normal';b.appendChild(x)}
function draw(){if(!isChat())return;const box=document.querySelector('#view .chat');if(!box)return;const uid=ses()?.user?.id;box.innerHTML=rows.map(r=>`<div class="bubble ${r.user_id===uid?'mine':''}"><b>${esc(r.user_id===uid?'Você':r.member_name||'Integrante')}</b><p>${esc(r.message)}</p><small>${new Date(r.created_at).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</small></div>`).join('')||'<div class="muted">Nenhuma mensagem ainda.</div>';localStorage.setItem('ieadjo_chat_unread','0');badge(0)}
function alertNew(r){if(isChat()&&document.visibilityState==='visible')return;if('Notification'in window&&Notification.permission==='granted'){try{new Notification('IEADJO • Nova mensagem',{body:(r.member_name||'Integrante')+': '+r.message,icon:'/igreja-hq.jpg',tag:'ieadjo-chat-'+r.id})}catch{}}}
async function poll(){if(busy||!ses()?.access_token)return;busy=true;try{const next=await api('/rest/v1/ieadjo_chat_messages?select=id,user_id,member_name,message,created_at&order=created_at.asc&limit=100');if(!next)return;const uid=ses()?.user?.id,newest=next.at(-1);if(lastId!==null&&newest&&String(newest.id)!==String(lastId)){const pos=next.findIndex(x=>String(x.id)===String(lastId));const fresh=(pos>=0?next.slice(pos+1):[newest]).filter(x=>x.user_id!==uid);if(fresh.length&&!isChat()){const n=Number(localStorage.getItem('ieadjo_chat_unread')||0)+fresh.length;localStorage.setItem('ieadjo_chat_unread',String(n));badge(n);alertNew(fresh.at(-1))}}rows=next;if(newest)lastId=newest.id;draw()}catch(e){console.warn('Chat indisponível temporariamente')}finally{busy=false}}
async function send(){const input=document.getElementById('msg'),text=input?.value.trim(),s=ses();if(!text||!s?.user?.id)return;input.value='';const p=prof();await api('/rest/v1/ieadjo_chat_messages',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({user_id:s.user.id,member_name:p.name||s.user.user_metadata?.full_name||'Integrante',message:text})});setTimeout(poll,100)}
document.addEventListener('click',e=>{if(e.target.closest('#send')&&isChat()){e.preventDefault();e.stopImmediatePropagation();send();return}if(e.target.closest('[data-go="chat"]')){localStorage.setItem('ieadjo_chat_unread','0');badge(0);setTimeout(()=>{draw();poll()},100)}},true);
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target?.id==='msg'&&isChat()){e.preventDefault();send()}},true);
function requestNotifications(){if(!('Notification'in window)||Notification.permission!=='default')return;Notification.requestPermission().catch(()=>{})}
document.addEventListener('click',requestNotifications,{once:true,capture:false});
badge(Number(localStorage.getItem('ieadjo_chat_unread')||0));setTimeout(poll,1200);setInterval(poll,6000);
})();