(()=>{
if(window.__ieadjoChatSafe)return;window.__ieadjoChatSafe=true;
const U='https://fzpffyouubmbxfwycywg.supabase.co',K='sb_publishable_fqG3I5cRWBXjn-EP0FoATA_0-SWvfsR',VAPID='BCwwFY4buXzi4PAB8V_-3Zd6KNBzzPT-V2tBBpTOxA5wVSAsBzGGoj9BkQKkBl8Zk2gqzVDS8ptoRzYXvpk9UqE';
let rows=[],lastId=null,busy=false,realtimeStarted=false;
const getJSON=k=>{try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return null}};
const ses=()=>getJSON('ieadjo_member_session');const prof=()=>getJSON('ieadjo_member_profile')||{};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function api(path,opt={}){const s=ses();if(!s?.access_token)return null;const r=await fetch(U+path,{...opt,cache:'no-store',headers:{apikey:K,Authorization:'Bearer '+s.access_token,'Content-Type':'application/json',...(opt.headers||{})}});if(!r.ok)return null;if(r.status===204)return[];try{return await r.json()}catch{return[]}}
function isChat(){return document.querySelector('#view .pagehead h1')?.textContent.trim()==='Chat geral'}
function badge(n){document.querySelectorAll('[data-chat-badge]').forEach(x=>x.remove());if(!n)return;const b=document.querySelector('.nav [data-go="chat"]');if(!b)return;b.style.position='relative';const x=document.createElement('i');x.dataset.chatBadge='1';x.textContent=n>9?'9+':String(n);x.style.cssText='position:absolute;top:7px;right:18px;background:#d64545;color:#fff;border-radius:20px;min-width:17px;height:17px;padding:0 4px;font:700 10px/17px sans-serif;font-style:normal';b.appendChild(x)}
function notifyCard(){if(!isChat()||document.getElementById('chatNotifyCard'))return;const chat=document.querySelector('#view .chat');if(!chat)return;const d=document.createElement('div');d.id='chatNotifyCard';d.style.cssText='background:#fff8e8;border:1px solid #ead8ae;border-radius:14px;padding:11px 12px;margin:0 0 10px;display:flex;align-items:center;justify-content:space-between;gap:10px';d.innerHTML=`<div><b style="font-size:12px">🔔 Notificações do chat</b><small id="chatNotifyText" style="display:block;color:#6c7a89;margin-top:2px">Ative para receber mensagens no celular.</small></div><button id="chatNotifyBtn" style="border:0;border-radius:10px;background:#0e2a47;color:#fff;padding:9px 10px;font-size:11px;font-weight:900">Ativar</button>`;chat.parentNode.insertBefore(d,chat);refreshNotifyState()}
async function refreshNotifyState(){const b=document.getElementById('chatNotifyBtn'),t=document.getElementById('chatNotifyText');if(!b||!t)return;try{const reg=await navigator.serviceWorker?.ready,sub=await reg?.pushManager?.getSubscription();if(Notification.permission==='granted'&&sub){b.textContent='✓ Ativadas';b.disabled=true;b.style.opacity='.65';t.textContent='Você receberá aviso quando chegar mensagem.'}else if(Notification.permission==='denied'){b.textContent='Bloqueadas';b.disabled=true;t.textContent='Permita notificações nas configurações do navegador/celular.'}}catch{}}
function b64urlToUint8Array(base64String){const padding='='.repeat((4-base64String.length%4)%4),base64=(base64String+padding).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(base64);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
async function enablePush(){if(!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window)){alert('Este aparelho/navegador não oferece notificações push.');return}const perm=await Notification.requestPermission();if(perm!=='granted'){refreshNotifyState();return}const reg=await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64urlToUint8Array(VAPID)});const j=sub.toJSON(),s=ses();await api('/rest/v1/ieadjo_push_subscriptions?on_conflict=endpoint',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({user_id:s.user.id,endpoint:j.endpoint,p256dh:j.keys?.p256dh,auth:j.keys?.auth,updated_at:new Date().toISOString()})});refreshNotifyState()}
function beep(){try{const C=window.AudioContext||window.webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=880;g.gain.setValueAtTime(.12,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.18);o.start();o.stop(c.currentTime+.18)}catch{}}
function draw(){if(!isChat())return;const box=document.querySelector('#view .chat');if(!box)return;const uid=ses()?.user?.id;box.innerHTML=rows.map(r=>`<div class="bubble ${r.user_id===uid?'mine':''}"><b>${esc(r.user_id===uid?'Você':r.member_name||'Integrante')}</b><p>${esc(r.message)}</p><small>${new Date(r.created_at).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</small></div>`).join('')||'<div class="muted">Nenhuma mensagem ainda.</div>';localStorage.setItem('ieadjo_chat_unread','0');badge(0);notifyCard()}
function onIncoming(r){const uid=ses()?.user?.id;if(String(r.user_id)===String(uid))return;if(!rows.some(x=>String(x.id)===String(r.id)))rows.push(r);lastId=r.id;if(isChat()&&document.visibilityState==='visible'){beep();draw()}else{const n=Number(localStorage.getItem('ieadjo_chat_unread')||0)+1;localStorage.setItem('ieadjo_chat_unread',String(n));badge(n);beep()}}
async function poll(){if(busy||!ses()?.access_token)return;busy=true;try{const next=await api('/rest/v1/ieadjo_chat_messages?select=id,user_id,member_name,message,created_at&order=created_at.asc&limit=100');if(!next)return;rows=next;const newest=next.at(-1);if(newest)lastId=newest.id;draw()}finally{busy=false}}
async function pushMessage(messageId){const s=ses();try{await fetch(U+'/functions/v1/ieadjo-chat-push',{method:'POST',headers:{apikey:K,Authorization:'Bearer '+s.access_token,'Content-Type':'application/json'},body:JSON.stringify({message_id:messageId})})}catch{}}
async function send(){const input=document.getElementById('msg'),text=input?.value.trim(),s=ses();if(!text||!s?.user?.id)return;input.value='';const p=prof(),created=await api('/rest/v1/ieadjo_chat_messages',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({user_id:s.user.id,member_name:p.name||s.user.user_metadata?.full_name||'Integrante',message:text})});const row=created?.[0];if(row?.id)pushMessage(row.id);setTimeout(poll,80)}
async function startRealtime(){if(realtimeStarted||!ses()?.access_token)return;realtimeStarted=true;try{if(!window.supabase){await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.4/dist/umd/supabase.min.js';s.onload=res;s.onerror=rej;document.head.appendChild(s)})}const client=window.supabase.createClient(U,K);const s=ses();if(s.refresh_token)await client.auth.setSession({access_token:s.access_token,refresh_token:s.refresh_token});client.channel('ieadjo-chat-live').on('postgres_changes',{event:'INSERT',schema:'public',table:'ieadjo_chat_messages'},p=>onIncoming(p.new)).subscribe()}catch(e){realtimeStarted=false;console.warn('Realtime indisponível; usando atualização periódica.')}}
document.addEventListener('click',e=>{if(e.target.closest('#chatNotifyBtn')){enablePush();return}if(e.target.closest('#send')&&isChat()){e.preventDefault();e.stopImmediatePropagation();send();return}if(e.target.closest('[data-go="chat"]')){localStorage.setItem('ieadjo_chat_unread','0');badge(0);setTimeout(()=>{draw();poll();notifyCard()},100)}},true);
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target?.id==='msg'&&isChat()){e.preventDefault();send()}},true);
badge(Number(localStorage.getItem('ieadjo_chat_unread')||0));setTimeout(()=>{poll();startRealtime()},700);setInterval(poll,15000);
})();