const CACHE='ieadjo-v28';
const ASSETS=['/','/manifest.webmanifest','/igreja-hq.jpg'];
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS)).catch(()=>{}));self.skipWaiting();});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()));});
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const u=new URL(event.request.url);
if(u.origin===location.origin&&(u.pathname==='/'||u.pathname==='/index.html')){event.respondWith(fetch(event.request,{cache:'no-store'}).catch(()=>caches.match(event.request)));return;}
if(u.origin===location.origin&&u.pathname==='/index-1.html'){event.respondWith(fetch(event.request,{cache:'no-store'}).then(async response=>{let html=await response.text();html=html.replace(/<script src="\/dynamic-repertorio\.js[^>]*><\/script>/g,'').replace(/<script src="\/dynamic-community\.js[^>]*><\/script>/g,'').replace(/<script src="\/dynamic-chat\.js[^>]*><\/script>/g,'').replace(/<script src="\/dynamic-team\.js[^>]*><\/script>/g,'').replace(/<script src="\/dynamic-weekly-leader\.js[^>]*><\/script>/g,'').replace(/<script src="\/attendance\.js[^>]*><\/script>/g,'');html=html.replace('</body>','<script src="/dynamic-repertorio.js?v=6"></script><script src="/dynamic-community.js?v=1"></script><script src="/dynamic-chat.js?v=2" defer></script><script src="/dynamic-team.js?v=1" defer></script><script src="/dynamic-weekly-leader.js?v=1" defer></script><script src="/attendance.js?v=1" defer></script></body>');return new Response(html,{status:response.status,statusText:response.statusText,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store, max-age=0'}})}).catch(()=>caches.match(event.request)));return;}
if(u.origin===location.origin&&(u.pathname==='/admin/'||u.pathname==='/admin/index.html')){event.respondWith(fetch(event.request,{cache:'no-store'}).then(async response=>{let html=await response.text();html=html.replace(/<script src="\/admin-song-links\.js[^>]*><\/script>/g,'').replace(/<script src="\/admin-weekly-leader\.js[^>]*><\/script>/g,'');html=html.replace('</body>','<script src="/admin-song-links.js?v=2"></script><script src="/admin-weekly-leader.js?v=1"></script></body>');return new Response(html,{status:response.status,statusText:response.statusText,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store, max-age=0'}})}).catch(()=>caches.match(event.request)));return;}
if(u.origin===location.origin&&['/dynamic-repertorio.js','/dynamic-community.js','/dynamic-chat.js','/dynamic-team.js','/dynamic-weekly-leader.js','/attendance.js','/admin-song-links.js','/admin-weekly-leader.js'].includes(u.pathname)){event.respondWith(fetch(event.request,{cache:'no-store'}));return;}
event.respondWith(fetch(event.request).then(response=>{const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(event.request,copy)).catch(()=>{});return response;}).catch(()=>caches.match(event.request).then(r=>r||caches.match('/'))));});